### PR TITLE
Rename examples to get proper syntax highlighting in editors

### PR DESCRIPTION
**Pull request by xxzefgh**

### CODE REVIEW

**Comment by xxzefgh** [comment]
On second thought, maybe it is this way for security reasons? idk

**Comment by sandrodz** [comment]
Yes I think its better to keep them without filename, discouraging their use without properly going through each line. I don't see any security risk, but its better be safe than sorry.

**Comment by sandrodz** [comment]
Like this you've deleted all example files.

**Comment by xxzefgh** [comment]
@sandrodz I know 😛 just messed with `mv` and didn't check what I did

**Pull request closed without merging**
